#include <GUIConstantsEx.au3>
#include <MsgBoxConstants.au3>
#include "GuiFlatButton.au3"

Example()

;Example GUI with toolbar
Func Example()

    Local $hGUI, $idLabel, $aButtons, $iTbSize

    $hGUI = GUICreate("GuiFlatButton Ex2", 300, 200)
    GUISetBkColor(0x444444)

    $idLabel = GUICtrlCreateLabel("Click a button", 10, 180, 150, 30)
    GUICtrlSetColor(-1, 0xFFFFFF)

    $aButtons = createToolbar()
    $iTbSize = UBound($aButtons)

    GUISetState(@SW_SHOW, $hGUI)

    Local $i = 0
    Local $iMsg
    While 1
        $iMsg = GUIGetMsg()

        Switch $iMsg
            Case $GUI_EVENT_CLOSE
                ExitLoop

            Case $aButtons[0] To $aButtons[$iTbSize - 1]
                ConsoleWrite("1")
                GUICtrlSetData($idLabel, GuiFlatButton_Read($iMsg))

        EndSwitch

        Sleep(10)
    WEnd

    GUIDelete()
EndFunc   ;==>Example


Func createToolbar()
    Local $aButtons[6]
    Local $bkColor = 0x777777
    Local $textColor = 0xFFFFFF
    Local $borderColor = 0x999999
    Local $aBtnClrs[12] = [0x777777, 0xFFFFFF, $GUI_BKCOLOR_TRANSPARENT, 0x888888, 0xFFFFFF, $GUI_BKCOLOR_TRANSPARENT, 0x999999, 0xFFFFFF, $GUI_BKCOLOR_TRANSPARENT, 0x666666, 0xFFFFFF, $GUI_BKCOLOR_TRANSPARENT]

    For $i = 0 To UBound($aButtons) - 1
        $aButtons[$i] = GuiFlatButton_Create("B" & $i, $i * 50, 0, 50, 17)
        GuiFlatButton_SetColorsEx($aButtons[$i], $aBtnClrs)
    Next

    Return $aButtons
EndFunc   ;==>createToolbar
